### PR TITLE
Kt update base.html

### PR DESCRIPTION
**Pull request by kntiller**
Added generic base.html. Working on adding picture with Logo.

### CODE REVIEW

**Comment by kntiller** [comment]
Screen Shot 2019-04-15 at 10 08 27 PM

**Review by chinhle23-zz — COMMENTED** [review]
I'm getting the error below when trying to navigate to: http://127.0.0.1:8000/core/ 
'Using the URLconf defined in monitorme.urls, Django tried these URL patterns, in this order:

__debug__/
admin/
^static/(?P<path>.*)$
The current path, core/, didn't match any of these.'

**Comment by kntiller** [comment]
This is in regard to the registration line that needed to be added. I added it locally as well as fixed the Index URL locally and page to get it work for testing purposes. Since the registration line is part of the PR that is pending from Aaron I did not include that in mine. 

UPDATED: I correct my response.... after reviewing the changes from Chin's branch, the core path was removed, and therefore would not work as my branch had the core path still being used. After reviewing and deciding on paths with new merged master, the code worked still. Added new screen shots to show working code.

**Comment by kntiller** [comment]
Screen Shot 2019-04-16 at 11 29 21 AM
Screen Shot 2019-04-16 at 11 29 09 AM

**Pull request merged**
